controller_manager_ns: ''
controller_list:
  - name: nao_dcm/LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
  - name: nao_dcm/RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
  - name: nao_dcm/Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - HeadYaw
      - HeadPitch
  - name: nao_dcm/LeftLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
  - name: nao_dcm/RightLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
#  - name: nao/Pelvis_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - LHipYawPitch
  - name: nao_dcm/LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LWristYaw
      - LHand
  - name: nao_dcm/RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RWristYaw
      - RHand

